name: e-com-api CI/CD work-flow

env:
  MONGO_DATABASE_URI: ${{ secrets.MONGO_DATABASE_URI_E_COM }}
  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME_E_COM }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD_E_COM }}
  KEY_JWT: ${{ secrets.KEY_JWT_E_COM }}
  DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD_E_COM}}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn test

  build:
    if: ${{ always() }}
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  deployment:
    if: ${{ always() }}
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Build app with pack CLI & publish
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy our Spring Boot app to fly.io
        run: flyctl deploy --remote-only
