name: e-com-api CI/CD work-flow

env:
  MONGO_DATABASE_URI: ${{ secrets.MONGO_DATABASE_URI_E_COM }}
  EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME_E_COM }}
  EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD_E_COM }}
  KEY_JWT: ${{ secrets.KEY_JWT_E_COM }}
  DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD_E_COM}}
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Test with Maven
        run: mvn test

  build:
    if: ${{ always() }}
    needs: [test]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify

  deployment:
    if: ${{ always() }}
    needs: [build]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GIT_TOKEN }}

      - name: Install pack CLI via the official buildpack Action https://github.com/buildpacks/github-actions#setup-pack-cli-action
        uses: buildpacks/github-actions/setup-pack@v4.8.1

      - name: Build app with pack CLI & publish to GitHub Container Registry
        run: |
          pack build ghcr.io/ericchentch/e-com-backend:latest \
              --builder paketobuildpacks/builder:tiny \
              --buildpack paketo-buildpacks/java-native-image@5.12.0 \
              --path . \
              --env "BP_JVM_VERSION=11" \
              --env "BP_NATIVE_IMAGE=true" \
              --cache-image ghcr.io/ericchentch/e-com-backend-paketo-cache-image:latest \
              --publish

      - name: Install flyctl via https://github.com/superfly/flyctl-actions
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy our Spring Boot app to fly.io
        run: flyctl deploy --image ghcr.io/ericchentch/e-com-backend:latest
