# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy to Azure

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        env:
          MONGO_DATABASE_URI: ${{ secrets.MONGO_DATABASE_URI_E_COM }}
          EMAIL_USERNAME: ${{ secrets.EMAIL_USERNAME_E_COM }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD_E_COM }}
          KEY_JWT: ${{ secrets.KEY_JWT_E_COM }}
          DEFAULT_PASSWORD: ${{ secrets.DEFAULT_PASSWORD_E_COM}}
        run: mvn clean install

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'e-com-backend'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_089DB6A383254AA99A2536367EDFFA1A }}
          package: '${{ github.workspace }}/target/e-com-0.0.1-SNAPSHOT.jar'

